spring: 
  profiles: 
    active: 
    - dev
---
server:
  port: 8781

spring: 
  profiles: dev 
  application: 
    name: znzj-user-service-dev

eureka:
  instance: 
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.application.name}:${server.port}
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/

info: 
  app.name: ${spring.application.name}
  company.name: www.xpj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
spring: 
   application:
     name: znzj-user-service
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     platform: mysql
     url: jdbc:mysql://localhost:3306/znzj?useUnicode=true&characterEncoding=utf-8
     username: root
     password: ahui123321
   redis:
    host: 192.168.96.102 
    port: 6379
    password: ahui123321
    timeout: 5000 

mybatis: 
  type-aliases-package: com.znzj.model
  mapper-locations: classpath:mapper/**/*.xml

---
server:
  port: 8781

spring: 
  profiles: test
  application: 
    name: znzj-user-service-test

eureka:
  instance: 
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.application.name}:${server.port}
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/

info: 
  app.name: ${spring.application.name}
  company.name: www.xpj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
spring: 
   application:
     name: znzj-user-service
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     platform: mysql
     url: jdbc:mysql://localhost:3306/znzj?useUnicode=true&characterEncoding=utf-8
     username: root
     password: ahui123321
   redis:
    host: 192.168.96.102 
    port: 6379
    password: ahui123321
    timeout: 5000 

mybatis: 
  type-aliases-package: com.znzj.model
  mapper-locations: classpath:mapper/**/*.xml

