spring: 
  profiles: 
    active: 
    - dev
  
---
server:
  port: 9527

spring:
  profiles: dev
  application:
    name: znzj-api-gateway
  redis:
    host: 121.201.65.111
    port: 6079
    password: ahui123321
    timeout: 5000 
    
eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true 

hystrix:
  command: 
    default:
      execution:
        isolation: 
          thread: 
            timeoutInMilliseconds: 15000
    
zuul: 
  #ignored-services: znzj-user-service
  prefix: /znzj
  ignored-services: "*"
  routes: 
    user.serviceId: znzj-user-service
    user.path: /user-service/**
    analyzer.serviceId: znzj-analyzer-service
    analyzer.path: /analyzer-service/**
    
info: 
  app.name:  ${spring.application.name}
  company.name: www.xph.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---

server:
  port: 9527

spring:
  profiles: test
  application:
    name: znzj-api-gateway
  redis:
    host: 192.168.1.11
    port: 6379
    password: ahui123321
    timeout: 5000 
    
eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
    
zuul: 
  #ignored-services: znzj-user-service
  prefix: /znzj
  ignored-services: "*"
  routes: 
    user.serviceId: znzj-user-service
    user.path: /user-service/**
    analyzer.serviceId: znzj-analyzer-service
    analyzer.path: /analyzer-service/**
    
hystrix:
  command: 
    default:
      execution:
        isolation: 
          thread: 
            timeoutInMilliseconds: 15000
    
info: 
  app.name:  ${spring.application.name}
  company.name: www.xph.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$