spring: 
  profiles: 
    active: 
    - dev
  
---
server:
  port: 9527

spring:
  profiles: dev
  application:
    name: znzj-api-gateway
  redis:
    host: 121.201.65.111
    port: 6079
    password: ahui123321
    timeout: 5000 
  http: 
    multipart: 
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
    
eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
    
zuul: 
  #ignored-services: znzj-user-service
  prefix: /znzj
  ignored-services: "*"
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Methods
  routes: 
    gateway.serviceId: znzj-api-gateway
    gateway.path: /gateway-service/**
    user.serviceId: znzj-user-service
    user.path: /user-service/**
    analyzer.serviceId: znzj-analyzer-service
    analyzer.path: /analyzer-service/**
    inspect.serviceId: znzj-inspect-service
    inspect.path: /inspect-service/**
    statistics.serviceId: znzj-statistics-service
    statistics.path: /statistics-service/**
  host: 
    socket-timeout-millis: 60000 
    connect-timeout-millis: 60000

  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 60000
          
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1  
  
sftp: 
  host: 121.201.65.111
  port: 6022
  username: root
  password: 123456
    
info: 
  app.name:  ${spring.application.name}
  company.name: www.xph.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---

server:
  port: 9527

spring:
  profiles: test
  application:
    name: znzj-api-gateway
  redis:
    host: 192.168.1.11
    port: 6379
    password: ahui123321
    timeout: 5000 
  http: 
    multipart: 
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
    
eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
    
zuul: 
  #ignored-services: znzj-user-service
  prefix: /znzj
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Methods
  ignored-services: "*"
  routes: 
    gateway.serviceId: znzj-api-gateway
    gateway.path: /gateway-service/**
    user.serviceId: znzj-user-service
    user.path: /user-service/**
    analyzer.serviceId: znzj-analyzer-service
    analyzer.path: /analyzer-service/**
    inspect.serviceId: znzj-inspect-service
    inspect.path: /inspect-service/**
    statistics.serviceId: znzj-statistics-service
    statistics.path: /statistics-service/**
  host: 
    socket-timeout-millis: 60000 
    connect-timeout-millis: 60000
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1  
  
sftp: 
  host: 121.201.65.111
  port: 6022
  username: root
  password: 123456
  
    
info: 
  app.name:  ${spring.application.name}
  company.name: www.xph.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
